created two controllers
Aleksandr-Slap/weather_api pull request #1
Opened 2023-03-01 18:53 UTC by Aleksandr-Slap

2023-03-01 19:08 UTC, VladimirShinkevich commented on app/controllers/weather_controller.rb
> +  URL_CURRENT = "http://dataservice.accuweather.com/currentconditions/v1/295212?".freeze
интерполяцию сюда делай ENV.fetch('API_KEY_WEATHER')

2023-03-01 19:08 UTC, VladimirShinkevich commented on app/controllers/weather_controller.rb
> +    response = HTTParty.get("#{URL_CURRENT}#{ENV[ 'API_KEY_WEATHER' ]}")
HTTParty.get(CURRENT_WEATHER_URL)

2023-03-01 19:08 UTC, VladimirShinkevich commented on app/controllers/weather_controller.rb
> +    render json: value
что в body ? скрин прикрепи сюда

2023-03-01 19:08 UTC, VladimirShinkevich commented on app/controllers/weather_controller.rb
> +    response = HTTParty.get("#{URL_HISTORY}#{ENV[ 'API_KEY_WEATHER' ]}")
тоже переделать, как выше

2023-03-01 19:08 UTC, VladimirShinkevich commented on app/controllers/weather_controller.rb
> +      values[time] = temp
historical_values[e['LocalObservationDateTime']] =e['Temperature']['Metric']['Value']

2023-03-01 19:34 UTC, VladimirShinkevich requested changes

2023-03-01 19:34 UTC, VladimirShinkevich commented on config/routes.rb
> +  get 'weather/current', to: 'weather#current'
https://gist.github.com/withoutwax/741c6e3c9a004c1463cbf7a1a3b719f8 
Посмотри как делать

2023-03-02 07:18 UTC, Aleksandr-Slap commented on app/controllers/weather_controller.rb
> +  URL_CURRENT = "http://dataservice.accuweather.com/currentconditions/v1/295212?".freeze
Сделал. Не понял зачем .fetch. Обошелся без него.

2023-03-02 07:20 UTC, Aleksandr-Slap commented on app/controllers/weather_controller.rb
> +    response = HTTParty.get("#{URL_HISTORY}#{ENV[ 'API_KEY_WEATHER' ]}")
Сделал

2023-03-02 07:22 UTC, Aleksandr-Slap commented on app/controllers/weather_controller.rb
> +      values[time] = temp
Очень круто! Сделал)

2023-03-02 07:35 UTC, Aleksandr-Slap commented on app/controllers/weather_controller.rb
> +    render json: value
![Снимок экрана 2023-03-02 в 10 24 36](https://user-images.githubusercontent.com/78231947/222361626-ec2bc102-ddce-4f94-a3bd-e1ffa232f4f4.png)


целиком не влез, но суть понятна(отчет за 24 ч)

2023-03-02 07:37 UTC, VladimirShinkevich commented on app/controllers/weather_controller.rb
> +  URL_CURRENT = "http://dataservice.accuweather.com/currentconditions/v1/295212?".freeze
если сделал надо пушить изменения, чтобы я посмотрел их. fetch нужен почитай для чего

2023-03-02 07:38 UTC, Aleksandr-Slap commented on app/controllers/weather_controller.rb
> +  URL_CURRENT = "http://dataservice.accuweather.com/currentconditions/v1/295212?".freeze
CURRENT_WEATHER_URL = "http://dataservice.accuweather.com/currentconditions/v1/295212?#{ENV['API_KEY_WEATHER']}".freeze

2023-03-02 07:38 UTC, Aleksandr-Slap commented on app/controllers/weather_controller.rb
> +    response = HTTParty.get("#{URL_CURRENT}#{ENV[ 'API_KEY_WEATHER' ]}")
Сделал

2023-03-02 08:32 UTC, VladimirShinkevich commented on app/controllers/weather_controller.rb
> +    body = JSON.parse(response.body)
```
weather_history = JSON.parse(response.body)
historical_values = {}
weather_history.each { historical_values[_1['LocalObservationDateTime'].to_time]  = _1['Temperature']['Metric']['Value'] } 
historical_values
```

2023-03-02 08:32 UTC, VladimirShinkevich commented on app/controllers/weather_controller.rb
> +    body = JSON.parse(response.body)
.to_time посмотри как работать с временем для преобразования в нужный формат

2023-03-02 08:32 UTC, VladimirShinkevich commented on app/controllers/weather_controller.rb
> +    body = JSON.parse(response.body)
перейди на постгрес

2023-03-02 18:23 UTC, Aleksandr-Slap commented on app/controllers/weather_controller.rb
> +    body = JSON.parse(response.body)
На постгрес завтра)
Применил to_time, но разницы не увидел, дата так и осталась строкой, думаю применить .gsub

2023-03-02 18:24 UTC, Aleksandr-Slap commented on config/routes.rb
> +  get 'weather/current', to: 'weather#current'
Вова, посмотрел - сделал, но не понял по ходу до конца. Мои пути работают, но уж слишком сильно я для этого навернул

2023-03-02 18:42 UTC, VladimirShinkevich commented on app/controllers/weather/weather_controller.rb
> +      body = JSON.parse(response.body)
Переменные правильно называй

2023-03-02 18:42 UTC, VladimirShinkevich commented on app/controllers/weather/weather_controller.rb
> +      value = body[0]['Temperature']['Metric']['Value']
Имя переменной, подумай как назвать...

2023-03-02 18:42 UTC, VladimirShinkevich commented on config/routes.rb
> +    get '/current', to: 'weather#current'
Почему он не в неймспейсе?
База постгрес должна быть

2023-03-02 18:42 UTC, VladimirShinkevich commented on app/controllers/weather/historical/weather_controller.rb
> +        body.each { |e| historical_values[e['LocalObservationDateTime'].to_time] =e['Temperature']['Metric']['Value'] }
Я писал, как надо сделать см. Выше

2023-03-02 18:42 UTC, VladimirShinkevich commented on app/controllers/weather/historical/weather_controller.rb
> +        render json: "#{ENV}".class
Вообще не понял, что это...?

2023-03-02 18:42 UTC, VladimirShinkevich commented on config/routes.rb
> +  namespace 'weather' do
А где  api?

2023-03-02 18:42 UTC, VladimirShinkevich commented on app/controllers/weather/historical/weather_controller.rb
> +module Weather
Module api

2023-03-02 18:42 UTC, VladimirShinkevich commented on app/controllers/weather/historical/weather_controller.rb
> +
Почему вынес этот экшн?

2023-03-03 10:58 UTC, VladimirShinkevich commented on app/controllers/weather/historical/weather_controller.rb
> +
надо сделать следующею иерархию
module Api
  class WeaterController
    actions....

в роутах соответственно
если не хочешь чтобы api был в пути читай доки по роутам (scope)

2023-03-03 12:14 UTC, Aleksandr-Slap commented on app/controllers/weather/historical/weather_controller.rb
> +        render json: "#{ENV}".class
Это я проверил класс переменной, когда разбирался с .fetch

2023-03-03 13:04 UTC, Aleksandr-Slap commented on app/controllers/weather/historical/weather_controller.rb
> +
Почитал и разобрался, двойная вложенность была лишней.
namespace 'weather' do
    get 'current', to: 'weather#current'
    get 'historical', to: 'weather#historical'
    get 'historical/max', to: 'weather#temp_max'
  end

2023-03-03 13:04 UTC, Aleksandr-Slap commented on app/controllers/weather/historical/weather_controller.rb
> +
Прости за отсутствие отступов!

2023-03-03 13:20 UTC, VladimirShinkevich commented on app/controllers/weather/historical/weather_controller.rb
> +        body.each { |e| hourly_temp[e['LocalObservationDateTime'].to_time] =e['Temperature']['Metric']['Value'] }
писал , как сделать
_1 вместо е

2023-03-03 13:20 UTC, VladimirShinkevich commented on app/controllers/weather/historical/weather_controller.rb
>          body = JSON.parse(response.body)
body тоже непонятное название

2023-03-03 13:20 UTC, VladimirShinkevich commented on app/controllers/weather/historical/weather_controller.rb
> +
снова не правильно, делай как я писал выше
нет наймспейсов, не правильная вложенность

2023-03-03 13:20 UTC, VladimirShinkevich commented on config/database.yml
> +  database: flatiron_mod3_development
странное название базы, посмотри как обычно их называют

2023-03-03 13:21 UTC, VladimirShinkevich commented on app/controllers/weather_controller.rb
> +    body = JSON.parse(response.body)
она и должна быть строкой

2023-03-15 17:12 UTC, VladimirShinkevich commented on Gemfile
> +  gem 'byebug'
gem 'pry-byebug'
  gem 'pry-rails'
эти получше

2023-03-15 17:12 UTC, VladimirShinkevich commented on app/services/request_to_weather_com.rb
> +class RequestToWeatherCom
1) заканчивается на service
2) weather create service
3) сервисы должны отвечать на метод call WeatherCreateService.call(....)
```
class Foo
  attr_accessor :a

  def initialize(a)
    @a = a
  end
  def self.call(a)
    new(a)
  end

  def g
    a + 5
  end
end
```

`t = Foo.call(3)`

или 

```
class Foo
  def self.call(a)
    a + 100
  end

end
```
но мне последний не очень, хотя для простой логики можно

4) предлагаю в моделе хранить 
min
max
avg
history (отсортированную)
тогда ты будешь знать, что нужно обращать к последней записи
рассмотри вариант если нам не нужно хранить историю более чем 24 часа другими словами не нужна модель и запись в БД, в таком случае можно создать [https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html](url)
5) каждый час запуская сервис в фоне
6) в контроллере уже можно обращаться к моделе
max_temp = Weather.last.max_temp и т.д

```
class BaseService
  def self.call(**args, &block)
    new(**args, &block).call
  end

end

class FooService < BaseService
  attr_accessor :task

  def initialize(task:)
    @task = task
  end

  def call
    ttt
  end

  def ttt
    task.class
  end

end
```
`g = Goo.call(task: 11)`
этот вариант думаю будет более понятнее

2023-03-15 17:12 UTC, VladimirShinkevich commented on app/models/weather.rb
> +class Weather < ApplicationRecord
не нашел где используется...

2023-03-15 17:12 UTC, VladimirShinkevich commented on app/services/request_to_weather_com.rb
> +  def self.response_body
получил данные за 24 часа , на руби создал массив из них , посчитал макс, мин, среднею засунул в модель

2023-03-15 17:12 UTC, VladimirShinkevich commented on test/controllers/weather_controller_test.rb
> +class WeatherControllerTest < ActionDispatch::IntegrationTest
не забудь про тесты

2023-03-15 17:12 UTC, VladimirShinkevich commented on app/controllers/api/v1/weathers_controller.rb
> +      def current
начинай узучать доки по гемам которые предложены к использованию

2023-03-20 14:56 UTC, VladimirShinkevich commented on app/controllers/api/v1/weathers_controller.rb
> +        hourly_temp = WeatheCreateService.historical_temp
1) WeatheCreateService откуда этот сервис?
2) контроллер надо переделать к Forecast надо обращаться
3) делай все исправления по ревью, только потом на проверку

2023-03-20 14:56 UTC, VladimirShinkevich commented on Gemfile
> +  gem 'byebug'
не поставил гемы

2023-03-20 14:56 UTC, VladimirShinkevich commented on app/services/forecast_create_service.rb
> +    Forecast.create!(max: @all_temp.max , min: @all_temp.min, avg: @avg.round(1), history: [@hourly_temp] )
1) что у тебя сервис возвращает?
2) ты зачем-то создаешь методы с инстансами это не совсем правильно, можно получить доступ к ним
3) проверь сколько запросов у тебя у ходит в текущем варианте на сервер?

2023-03-20 14:56 UTC, VladimirShinkevich commented on app/services/forecast_create_service.rb
> +    @respon_body = JSON.parse(response.body)
```
def call
  history = weather_history_in_24_hours
  
Forecast.create!(
  max: max_temp(history) , 
  min: min_temp(history), 
  avg: avg_temp(history), 
  history: history 
)

end

def weather_history_in_24_hours
  JSON.parse(HTTParty.get(HISTORY_WEATHER_URL)).map do |hour|
    { time: hour[time], temperature: hour[temperature] }
  end
end

def max_temp(history)
  history.map { _1[:temp] }.max
end

def min_temp(history)
   weather_history.map { _1[:temp] }.min
end

def avg_temp(history)
   history.map { _1[:temp] }.sum / history.size
end
```

2023-03-20 14:56 UTC, VladimirShinkevich commented on app/services/forecast_create_service.rb
> +class ForecastCreateService
1) покажи, как сервис вызываешь
2) ранее писал нужен base_service
3) нужен конструктор класса(сервиса)

2023-03-20 15:10 UTC, VladimirShinkevich commented on app/services/forecast_create_service.rb
> +    @respon_body = JSON.parse(response.body)
рассмотри вариант если нам не нужно хранить историю более чем 24 часа другими словами не нужна модель и запись в БД, в таком случае можно создать https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html

2023-03-29 16:35 UTC, VladimirShinkevich commented on app/controllers/api/v1/forecasts_controller.rb
> +        arr = Forecast.last.history.map do |hour|
можно select использовать и тогда compact не нужен

2023-03-29 16:35 UTC, VladimirShinkevich commented on app/controllers/api/v1/forecasts_controller.rb
> +        respone = arr.compact.empty? ? "404 Not Found" : arr.compact
тут если пустой будет ты в рендере отрисуешь "4"

2023-03-29 16:35 UTC, VladimirShinkevich commented on app/controllers/api/v1/forecasts_controller.rb
> +        respone = arr.compact.empty? ? "404 Not Found" : arr.compact
```
by_time = Forecast.last.history.select { _1["time"] == Time.at(params[:timestamp].to_i).to_time.beginning_of_hour.to_s }
render json: by_time.empty? ? "404 Not Found" : arr.join
```

2023-07-20 15:22 UTC, merged